#!/usr/bin/env bash
#Displays "To infinity and beyond" indefinitely and I am invincible!!! SIGTERM.
trap "echo I am invincible!!!" SIGTERM
while :
do
    echo "To infinity and beyond"
    sleep 2
done
